In [1]:
import numpy as np

In [2]:
np.ones(5) #5 tane 1 barındıran bir array oluşturun

array([1., 1., 1., 1., 1.])

In [60]:
np.zeros(5) #5 tane 0 barındıran bir array oluşturun

array([0., 0., 0., 0., 0.])

In [4]:
np.arange(2,100,2) #2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [6]:
np.ones(5)*10 #5 tane 10 bulunan bir array oluşturun

array([10., 10., 10., 10., 10.])

In [8]:
np.arange(1,17).reshape(4,4) #1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [9]:
np.eye(4) #4x4'lük bir birim matris oluşturun

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.randint(5) #0 ile 5 arasında rastgele değerler üretin

3

In [11]:
np.random.rand(25).reshape(5,5) #5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

array([[0.00609986, 0.00509603, 0.46067461, 0.85127825, 0.52817259],
       [0.58905455, 0.54823604, 0.5489693 , 0.45599178, 0.04387008],
       [0.80822468, 0.36248019, 0.1848179 , 0.35917012, 0.33483865],
       [0.2406359 , 0.05743625, 0.55401733, 0.26597282, 0.89180601],
       [0.16679051, 0.85886245, 0.67300705, 0.68893804, 0.4430831 ]])

In [12]:
np.linspace(1,5,20) #1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

* Array Indekslenmesi


In [5]:
import numpy as np

In [6]:
dizi   = np.arange(1,101).reshape(10,10)

In [7]:
dizi

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [8]:
dizi[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [14]:
dizi[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [15]:
dizi[:3,(2,3)]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [16]:
dizi[:3,1]

array([ 2, 12, 22])

In [18]:
dizi[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [20]:
dizi[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

* Array Operasyonları

In [50]:
arr1=np.random.randint(9,size=(3,3))

In [51]:
arr2=np.random.randint(9,size=(3,3))

In [52]:
arr1

array([[3, 8, 2],
       [1, 3, 5],
       [2, 0, 4]])

In [53]:
arr2

array([[5, 0, 7],
       [3, 3, 2],
       [1, 4, 0]])

In [54]:
arr1+arr2 # iki matrisi toplayın

array([[8, 8, 9],
       [4, 6, 7],
       [3, 4, 4]])

In [55]:
arr1*arr2 # iki matrisi çarpın

array([[15,  0, 14],
       [ 3,  9, 10],
       [ 2,  0,  0]])

In [56]:
arr1.mean() #arr1 matrisinin tüm elemanlarının ortalamasını bulun

3.111111111111111

In [57]:
arr2.mean() #arr2 matrisinin tüm elemanlarının ortalamasını bulun

2.7777777777777777

In [58]:
arr1.sum() #arr1 matrisinin tüm elemanlarının toplamını bulun

28

In [59]:
arr2.sum() #arr2 matrisinin tüm elemanlarının toplamını bulun

25