In [1]:
a=[1,2,3,4,5]
b=[6,7,8,9,0]

In [4]:
ab=[]
for i in range(0,len(a)):
    yeni=a[i]*b[i]
    ab.append(yeni)

In [5]:
ab

[6, 14, 24, 36, 0]

bunu kısayolla yapmak isyersem numpy araya giriyor

In [6]:
import numpy as np

In [10]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])

In [11]:
a*b

array([ 6, 14, 24, 36,  0])

# NumPy Array'i oluşturmak


In [12]:
import numpy as np

## 1)liste üzerinden array oluşturma

In [13]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [14]:
a=np.array([1,2,3,4,5,6])

In [15]:
type(a)

numpy.ndarray

In [18]:
np.array([1.13,2,3,5.7,6]) #NumPy tipi zorladığı için int değerlerin hep

array([1.13, 2.  , 3.  , 5.7 , 6.  ])

In [20]:
np.array([1.13,2,3,5.7,6],dtype="int") #tipi belirtirsek ona dönüştürür

array([1, 2, 3, 5, 6])

# 2)sıfırdan array olusturma

In [21]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.full((3,5),3,dtype=int) #sadece belirli bir sayıdan oluşturmak istiyorsam

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [24]:
np.arange(0,31,3) #0 dan 31 e kadar 3 er 3 er artacak şekilde bir doğrusal array oluşturur

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [25]:
np.linspace(0,1,10) #iki sayı arasında belirli bir değer oluşturmak için kullanılır 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
np.random.normal(10,4,(3,4)) #dağılımı kendimiz belirledik

array([[10.01392746, 15.9143081 ,  3.05316671,  6.86900452],
       [ 8.3981044 , 13.28394633,  4.77833634, 12.94215135],
       [13.24683632, 19.77992639,  5.23073408,  1.57678526]])

In [28]:
np.random.randint(0,10,(3,3))  #int değerlerden rastgele oluşturulmus bir array

array([[8, 5, 8],
       [4, 7, 7],
       [4, 1, 1]])

## NumPy Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [29]:
import numpy as np

In [32]:
np.random.randint(10,size=10)

array([6, 3, 4, 7, 0, 4, 2, 4, 5, 3])

In [33]:
a=np.random.randint(10,size=10)

In [34]:
a.ndim

1

In [35]:
a.shape

(10,)

In [36]:
a.size

10

In [37]:
a.dtype

dtype('int32')

In [43]:
b=np.random.randint(10,size=(3,5))

In [44]:
b

array([[9, 5, 7, 0, 3],
       [9, 8, 5, 5, 6],
       [8, 4, 1, 7, 6]])

In [46]:
b.ndim

2

In [47]:
b.shape

(3, 5)

In [49]:
b.size

15

In [50]:
b.dtype

dtype('int32')

## yeniden şekillendirme "Reshape"

In [53]:
import numpy as np

In [83]:
a=np.arange(1,10)

In [84]:
a.ndim

1

In [85]:
a=np.arange(1,10).reshape((3,3)) # tek boyutlu vektörü çok boyutlu matrise çevirdim

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
a.ndim

2

In [77]:
a=np.arange(1,10)

In [78]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a.ndim

1

In [80]:
b=a.reshape((1,9)) #tek boyuttan çok boyuta ama tek boyut bilgilerini taşıyacak

In [81]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [82]:
b.ndim

2

## array birleştirme "Concatenate"

In [88]:
import numpy as np 

In [89]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [91]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [92]:
z=np.array([7,8,9])

In [93]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**iki boyutlu birleştirme**

In [106]:
a=np.random.randint(0,9,(3,3))
b=np.random.randint(5,10,(3,3))

In [107]:
a

array([[6, 5, 3],
       [3, 6, 1],
       [8, 1, 1]])

In [108]:
b

array([[9, 5, 9],
       [5, 8, 6],
       [6, 9, 7]])

In [109]:
np.concatenate([a,b])

array([[6, 5, 3],
       [3, 6, 1],
       [8, 1, 1],
       [9, 5, 9],
       [5, 8, 6],
       [6, 9, 7]])

In [111]:
np.concatenate([a,b],axis=1) #sütuna göre(1)
                             # satıra göre olsaydı(0)

array([[6, 5, 3, 9, 5, 9],
       [3, 6, 1, 5, 8, 6],
       [8, 1, 1, 6, 9, 7]])

## Array ayırma "split"

In [112]:
import numpy as np

In [114]:
x=np.array([1,2,3,4,4,5,6,7,8,9])

In [116]:
np.split(x,[2,6])

[array([1, 2]), array([3, 4, 4, 5]), array([6, 7, 8, 9])]

In [117]:
a,b,c=np.split(x,[2,6])

In [118]:
a

array([1, 2])

In [119]:
b

array([3, 4, 4, 5])

In [120]:
c

array([6, 7, 8, 9])

**iki boyutlu ayırma**

In [2]:
import numpy as np

In [3]:
a=np.arange(16).reshape(4,4)

In [4]:
a.ndim

2

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.vsplit(a,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [7]:
np.vsplit(a,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [8]:
x,y=np.vsplit(a,[3])

In [9]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
y

array([[12, 13, 14, 15]])

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.hsplit(a,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [14]:
sağ,sol=np.hsplit(a,[3])

In [17]:
sağ

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [18]:
sol

array([[ 3],
       [ 7],
       [11],
       [15]])

## Array sıralama "sort"

In [19]:
import numpy as np

In [20]:
s=np.array([2,5,3,7,4,1,])

In [21]:
s

array([2, 5, 3, 7, 4, 1])

In [22]:
np.sort(s) #numpy içerisinden çagırdıgım için verinin orijinal yapısını bozmadı

array([1, 2, 3, 4, 5, 7])

In [23]:
s.sort() #yapı bozuldu küçükten büyüğe sıralandı

In [24]:
s

array([1, 2, 3, 4, 5, 7])

**iki boyutlu sıralama**

In [33]:
a=np.random.randint(0,16,(4,4))

In [34]:
a

array([[14,  1,  2,  8],
       [ 9,  5,  2, 13],
       [ 8, 15,  3,  0],
       [ 1,  3,  7,  1]])

In [36]:
np.sort(a,axis=1)

array([[ 1,  2,  8, 14],
       [ 2,  5,  9, 13],
       [ 0,  3,  8, 15],
       [ 1,  1,  3,  7]])

In [37]:
np.sort(a,axis=0)

array([[ 1,  1,  2,  0],
       [ 8,  3,  2,  1],
       [ 9,  5,  3,  8],
       [14, 15,  7, 13]])