## İndex ile elemanlara erişmek

In [2]:
import numpy as np
a=np.random.randint(10,size=10)
a

array([9, 6, 1, 4, 9, 9, 8, 8, 2, 9])

In [3]:
a[0]

9

In [4]:
a[-1]

9

In [5]:
a[0]=100

In [6]:
a

array([100,   6,   1,   4,   9,   9,   8,   8,   2,   9])

* iki boyutlu

In [8]:
m=np.random.randint(10,size=(3,5))
m

array([[1, 4, 3, 6, 2],
       [7, 1, 7, 9, 3],
       [8, 6, 4, 2, 8]])

In [9]:
m[0,0]

1

In [12]:
m[2,3]

2

In [13]:
m[2,3]=5

In [14]:
m

array([[1, 4, 3, 6, 2],
       [7, 1, 7, 9, 3],
       [8, 6, 4, 5, 8]])

In [15]:
m[1,4]

3

In [18]:
m[1,4]=2.8 #var olan bir array'e dışardan array dışı farklı bir tip ekleme yapmak isteğimizde kabul etmez ve çevirir

In [17]:
m

array([[1, 4, 3, 6, 2],
       [7, 1, 7, 9, 2],
       [8, 6, 4, 5, 8]])

In [19]:
# 0 dan oluşturduğumuz bir array'de float değer varsa bütün arrayin tipini ondalıklı olarak görür

## Array alt küme işlemleri(slicing)

In [20]:
import numpy as np

In [21]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
a[0:3]

array([20, 21, 22])

In [23]:
a[:3]

array([20, 21, 22])

In [24]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [25]:
a[1::2]

array([21, 23, 25, 27, 29])

* iki boyutlu

In [28]:
import numpy as np
m=np.random.randint(10,size=(5,5))
m

array([[0, 6, 4, 4, 8],
       [0, 2, 8, 0, 8],
       [8, 0, 0, 8, 7],
       [9, 2, 7, 4, 1],
       [9, 6, 3, 2, 5]])

In [30]:
m[:,0]  #tüm satırı al ve 0. sütunu seç

array([0, 0, 8, 9, 9])

In [31]:
m[:,4]  #4. sütunu seçtik

array([8, 8, 7, 1, 5])

In [33]:
m[0,:] #ilk satırı çektik

array([0, 6, 4, 4, 8])

In [35]:
m[2,:] #2. satırı çektik

array([8, 0, 0, 8, 7])

In [36]:
m[0:2,0:3]

array([[0, 6, 4],
       [0, 2, 8]])

In [37]:
m[:,0:2]

array([[0, 6],
       [0, 2],
       [8, 0],
       [9, 2],
       [9, 6]])

In [38]:
m[1:3,0:2]

array([[0, 2],
       [8, 0]])

## Alt küme üzerinde işlem yapmak

In [39]:
import numpy as np
a=np.random.randint(10,size=(5,5))
a

array([[5, 2, 7, 3, 1],
       [3, 2, 8, 4, 4],
       [7, 9, 9, 8, 5],
       [0, 9, 0, 2, 6],
       [8, 1, 8, 6, 4]])

In [42]:
alt_a=a[0:3,0:2]
alt_a

array([[5, 2],
       [3, 2],
       [7, 9]])

In [43]:
alt_a[0,0]=987666
alt_a[1,1]=2344

In [44]:
alt_a

array([[987666,      2],
       [     3,   2344],
       [     7,      9]])

In [45]:
a

array([[987666,      2,      7,      3,      1],
       [     3,   2344,      8,      4,      4],
       [     7,      9,      9,      8,      5],
       [     0,      9,      0,      2,      6],
       [     8,      1,      8,      6,      4]])

* sadece alt kümede değişiklik yapıp ana kümemin etkilenmesini istemiyor olabilirim bunun için

In [46]:
m=np.random.randint(10,size=(5,5))
m

array([[5, 4, 8, 5, 2],
       [1, 5, 6, 8, 2],
       [0, 7, 8, 4, 8],
       [9, 6, 2, 2, 5],
       [6, 3, 4, 1, 4]])

In [48]:
alt_m=m[0:3,0:2].copy() #seçmiş olduğumuz alt kümeyi ana array'den ayırır
alt_m

array([[5, 4],
       [1, 5],
       [0, 7]])

In [49]:
alt_m[0,1]=654
alt_m[2,0]=444

In [50]:
alt_m

array([[  5, 654],
       [  1,   5],
       [444,   7]])

In [51]:
m

array([[5, 4, 8, 5, 2],
       [1, 5, 6, 8, 2],
       [0, 7, 8, 4, 8],
       [9, 6, 2, 2, 5],
       [6, 3, 4, 1, 4]])

## Fancy ındex ile elemanlara erişmek 

In [52]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [53]:
v[1]

3

In [54]:
v[3]

9

In [55]:
v[5]

15

In [56]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [57]:
al_getir=[1,3,5]

In [58]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [59]:
v[al_getir]

array([ 3,  9, 15])

* iki boyutta fancy

In [62]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
satır=[0,1]
sütun=[1,2]

In [65]:
m[satır,sütun]

array([1, 5])

#basit index ile fancy index

In [66]:
m


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
m[0,[1,2]] #fancy birden fazla eleman seçmek için liste veya numpy dizisinde kullanılır

array([1, 2])

In [72]:
m[1:,[0,1]]

array([[3, 4],
       [6, 7]])

#slice ile fancy index

In [70]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## koşullu eleman işlemleri

In [74]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [75]:
v<3

array([ True,  True, False, False, False])

In [76]:
v[v<3]

array([1, 2])

In [78]:
v[v>=3]

array([3, 4, 5])

In [79]:
v[v==3]

array([3])

In [80]:
v[v!=3]

array([1, 2, 4, 5])

In [81]:
v

array([1, 2, 3, 4, 5])

In [82]:
v/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [83]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [84]:
v**2

array([ 1,  4,  9, 16, 25])

## Matematiksel işlemler

In [86]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [87]:
v-1

array([0, 1, 2, 3, 4])

In [88]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [89]:
#ufunc

In [90]:
np.subtract(v,1)  # v-1

array([0, 1, 2, 3, 4])

In [91]:
np.add(v,1)  # v+1

array([2, 3, 4, 5, 6])

In [92]:
np.multiply(v,4)  #v*4

array([ 4,  8, 12, 16, 20])

In [93]:
np.divide(v,3)  #v/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [94]:
np.power(v,3)  #v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [95]:
np.mod(v,2)  #v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [96]:
np.absolute(np.array([-3]))  #mutlak değer

array([3])

In [97]:
np.sin(360)

0.9589157234143065

In [99]:
np.cos(180)

-0.5984600690578581

In [101]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [103]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

## Numpy ile iki bilinmeyenli denklem çözümü

In [104]:
import numpy as np


5*x0+x1=12
x0+3*x1=10

In [108]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [109]:
a

array([[5, 1],
       [1, 3]])

In [110]:
b

array([12, 10])

In [111]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])