In [1]:
import numpy as np

In [3]:
a=np.array([1,2,5,4,3,7,6]) #liste üzerinden array olusturma

In [4]:
type(a)

numpy.ndarray

In [16]:
np.arange(0,20) #sıfırdan array oluşturma

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
a=np.random.randint(0,20,(4,5)) #sıfırdan array olusturma

In [9]:
a

array([[18,  0,  4, 11,  2],
       [ 2, 18,  3, 18,  8],
       [16, 12,  3, 14, 14],
       [ 4,  2, 18,  9, 12]])

In [10]:
a.ndim #boyut sayısı

2

In [12]:
a.shape #boyut bilgisi

(4, 5)

In [13]:
a.size #eleman sayısı

20

In [14]:
a.dtype # array veri tipi

dtype('int32')

In [63]:
np.arange(0,20).reshape((4,5)) #tek boyuttan çok boyuta çevirmek

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
a=np.arange(1,10)  # tek boyuttan çok boyuta çevirmek

In [22]:
b=a.reshape(1,9)

In [23]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
b.ndim

2

In [25]:
x=np.array([0,9,8,7])
y=np.array([6,5,4,3])

In [26]:
np.concatenate([x,y]) #birleştirme

array([0, 9, 8, 7, 6, 5, 4, 3])

In [34]:
e=np.random.randint(1,10,(4,3))
t=np.random.randint(0,16,(4,3))

In [35]:
np.concatenate([e,t]) #satıra göre sıraladık,çok boyutlu birleştirme

array([[ 3,  2,  7],
       [ 1,  7,  3],
       [ 3,  9,  2],
       [ 9,  1,  9],
       [ 8,  9,  6],
       [10, 10,  4],
       [ 7, 12,  1],
       [ 0, 11, 12]])

In [36]:
np.concatenate([e,t],axis=1)

array([[ 3,  2,  7,  8,  9,  6],
       [ 1,  7,  3, 10, 10,  4],
       [ 3,  9,  2,  7, 12,  1],
       [ 9,  1,  9,  0, 11, 12]])

In [37]:
x=np.array([1,2,3,4,5,6,7,8,9,0]) #tek boyutlu ayırma

In [39]:
np.split(x,[3,7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([8, 9, 0])]

In [42]:
a=np.arange(16) #çift boyutlu ayırma

In [43]:
b=np.arange(16).reshape(4,4)

In [44]:
b.ndim

2

In [45]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.split(b,[1,3],axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [59]:
a=np.random.randint(0,20,[4,5]) #çift boyutlu ayırma

In [60]:
a

array([[ 4, 10, 18,  6,  4],
       [ 8, 12,  4,  3, 11],
       [ 8,  0, 10, 19,  1],
       [10, 17,  2, 12,  7]])

In [61]:
np.vsplit(a,[3])

[array([[ 4, 10, 18,  6,  4],
        [ 8, 12,  4,  3, 11],
        [ 8,  0, 10, 19,  1]]),
 array([[10, 17,  2, 12,  7]])]

In [62]:
np.hsplit(a,[3])

[array([[ 4, 10, 18],
        [ 8, 12,  4],
        [ 8,  0, 10],
        [10, 17,  2]]),
 array([[ 6,  4],
        [ 3, 11],
        [19,  1],
        [12,  7]])]

In [64]:
a=np.array([3,5,4,3,6,4,9,7])


In [65]:
np.sort(a) #yapı bozulmadı

array([3, 3, 4, 4, 5, 6, 7, 9])

In [67]:
a.sort() #yapı bozuldu

In [68]:
a

array([3, 3, 4, 4, 5, 6, 7, 9])

In [69]:
a=np.random.randint(0,16,(4,4))

In [70]:
a

array([[15, 14, 11,  1],
       [ 1,  2, 12, 10],
       [15,  6, 11, 15],
       [13, 13, 11,  9]])

In [72]:
np.sort(a,axis=0)

array([[ 1,  2, 11,  1],
       [13,  6, 11,  9],
       [15, 13, 11, 10],
       [15, 14, 12, 15]])